config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :uploads, only: [:index] do
    collection { post :import }
  end
  
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/importer.rb
require 'csv'
class Importer
  
  # Expects the following csv header items
  # "purchaser_name", "item_description", item_price", 
  # "purchase_count", "merchant_address" "merchant_name"
  def self.import(file)
    importer = self.new
    importer.perform_import file
  end

  def perform_import(file)
    CSV.foreach(file.path, headers: true) do |row|
      row = row.to_hash.symbolize_keys
      item = create_item row[:item_description], row[:item_price]
      create_purchaser row[:purchaser_name]
      create_address row[:merchant_address]
      create_merchant row[:merchant_name]
      create_order
      create_order_item row[:purchase_count]
    end
    calculate_revenue
  end
  
  private
  
  def create_item(name, price)
    @item = Item.where(name: name, price: price).first_or_create!
  end

  def create_purchaser(name)
    @purchaser = Purchaser.where(name: name).first_or_create!
  end

  def create_address(name)
    @address = Address.where(name: name).first_or_create!
  end

  def create_merchant(name)
    @merchant = Merchant.where(name: name).first_or_create!(address_id: @address.id)
  end

  def create_order
    @order = Order.create!(purchaser_id: @purchaser.id)
  end

  def create_order_item(p_count)
    OrderItem.create!(
      order_id: @order.id,
      item_id: @item.id,
      quantity: p_count,
      merchant_id: @merchant.id
    )
  end
  
  def calculate_revenue
    total = 0
    OrderItem.includes(:item).each do |oi|
      total += (oi.quantity * oi.item.price)
    end
    total
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  belongs_to :address
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :purchaser
  has_many :items, through: :order_items
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :purchaser
  belongs_to :order
  belongs_to :item
end

app/models/purchaser.rb
class Purchaser < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
  end

  def import
    total = Importer.import(params[:file])
    redirect_to uploads_url, notice: "Data imported. Total revenue: #{total}"
  end


end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:uploads, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DealADay" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">DealADay</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "Logout", :logout, method: :post %></li>
            <% else %>
              <li><%= link_to "Login", :login %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div> <!-- /container -->

  </body>
</html>

app/views/uploads/index.html.erb
<h2>Import Data</h2>
<%= form_tag import_uploads_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Deal a Day!</h1>
<h2>Login to import Files</h2>